language: csharp
solution: ApiGateway.sln
mono: none
dist: xenial
sudo: required
dotnet: 6.0
script:
 - dotnet restore
 - dotnet build
 - dotnet test AspNetCore.ApiGateway.Tests/AspNetCore.ApiGateway.Tests.csproj
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1